### ISSUE TITLE
Feature Request: Callback for extensibility

### ISSUE THREAD

**Issue by jsendros** [brianPlummer/TinyDancer#10]
Allow users to extend the value of this tool easily. A callback called on each doFrame() which forwards the time between VSync and the dropped frames you've calculated could be valuable. The overlay is great, though extensibility here allows other devs to leverage the work you've done to simplify their performance measuring problems.

**Comment by digitalbuddha** [comment]
https://github.com/brianPlummer/TinyDancer/pull/14
