### ISSUE TITLE
Unable to start on Marshmallow

### ISSUE THREAD

**Issue by ursusursus** [brianPlummer/TinyDancer#11]
java.lang.RuntimeException: Unable to start service com.codemonkeylabs.fpslibrary.service.FPSService@6be9f23 with Intent { cmp=my.cool.app/com.codemonkeylabs.fpslibrary.service.FPSService (has extras) }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@d29dcdd -- permission denied for this window type

**Comment by digitalbuddha** [comment]
Right marshmallow and stuff.  Will add permission request.

**Comment by digitalbuddha** [comment]
You can enable that permission on your  own through settings fyi...http://stackoverflow.com/questions/32061934/permission-from-manifest-doesnt-work-in-android-6

I'll add something to the Readme as well as implement the programmatic hack later today.

**Comment by digitalbuddha** [comment]
@ursusursus are you developing a lock screen app by any chance?

**Comment by brianPlummer** [comment]
@ursusursus i just committed the fix and will bump up our revision number.  Please let me know if it still does not work.  Thanks!!
