### ISSUE TITLE
TinyDancer widget stays on screen even when application process is killed.

### ISSUE THREAD

**Issue by magillus** [brianPlummer/TinyDancer#15]
I noticed that TinyDancer widget stays on screen even when application process is killed, in matter of fact I killed all applications and still see it.

Widget went away after going to application manager -> my app and "force stop" it.

It happened on Samsung Note Edge 5.0.1.

Can we add touch event for long press on the widget with dialog popup to kill it?

**Comment by magillus** [comment]
I think that was case because of some service was running in my app, application wasn't destroyed.

**Comment by digitalbuddha** [comment]
I'm going to reopen.  I'd like to find a better way to turn off when app gets paused. You can also call '' 'hide''' if you keep a reference to the tiny builder.

**Comment by digitalbuddha** [comment]
Thanks for using our lib. Open enhancement issues if you'd need any Add'l hooks or features.

**Comment by brianPlummer** [comment]
@magillus "Can we add touch event for long press on the widget with dialog popup to kill it?" great idea!  I'll implement something over the weekend to accommodate your request.  Thank you for the feedback and request!

**Comment by magillus** [comment]
@brianPlummer thank you for great library - I saw the FPS measuring presentation on DroidconNYC and thought about it - just lack of time, glad you got it nice finished.

**Comment by brianPlummer** [comment]
@magillus Hey there! Double tapping on overlay will now hide it! I just pushed it up.  Sorry for the lateness of it.  https://github.com/brianPlummer/TinyDancer/pull/20  The new library rev will be 0.0.7, I will update the documentation when the new rev becomes available on maven central.  Cheers!

**Comment by Rainer-Lang** [comment]
Thanks.
