### ISSUE TITLE
Lower minSdkVersion ?

### ISSUE THREAD

**Issue by robertoestivill** [brianPlummer/TinyDancer#18]
Any particular api call or functionality strictly depending on api level 16 ?
Wondering if it's feasible to lower it to 14 to support more devices.

Thanks
Robert

**Comment by digitalbuddha** [comment]
Choreographer.FrameCallback is api 16+.  Unfortunately that is the basis of the library. What I can recommend is to make a debug/local build that has a higher sdk level than your real build and enable tiny dancer there.
