### ISSUE TITLE
What is the need for Application class in the hide function

### ISSUE THREAD

**Issue by aashrairavooru** [brianPlummer/TinyDancer#21]
```TinyDancer.hide(Application)``` takes an application instance but calls ```TinyDancerBuilder.hide(Context)```, this reduces the flexibility as you need to put an extra method in the application class.

**Comment by aashrairavooru** [comment]
Although you can do ```((Application) context.getApplicationContext())``` but still passing context should suffice

**Comment by digitalbuddha** [comment]
good suggestion. thanks for using. Let me know if anything else is out of place.

**Comment by aashrairavooru** [comment]
Thanks will do, can you do a release on this ASAP ☺

**Comment by digitalbuddha** [comment]
Release .8 has been submitted to maven, readme will be updated when it is actually live.
