### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by artem-zinnatullin** [brianPlummer/TinyDancer#23]
Please add `CHANGELOG.md` :)

// You can grab format from the `OkHttp` for example.

**Comment by digitalbuddha** [comment]
I guess I'm the only one that uses releases https://github.com/brianPlummer/TinyDancer/releases.  Will migrate notes from there to changelog

**Comment by artem-zinnatullin** [comment]
Thanks!

On Mon, Dec 14, 2015, 22:35 Mike Nakhimovich <notifications@github.com>
wrote:

> I guess I'm the only one that uses releases
> https://github.com/brianPlummer/TinyDancer/releases. Will migrate notes
> from there to changelog
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brianPlummer/TinyDancer/issues/23#issuecomment-164536577>
> .
>
-- 

@artem_zin
