### ISSUE TITLE
There was a typo in the class, TinyDancer, Content should be Context

### ISSUE THREAD

**Issue by funyoung** [brianPlummer/TinyDancer#26]
There was a typo in the class, TinyDancer, Content should be Context
-    public static void hide(Content context) {
+    public static void hide(Context context) {

And I include the jar within an app, and the class TinyDancer could not be recoganized, maybe it causes by the jar consist with the typo.

**Comment by digitalbuddha** [comment]
Oops good find will fix.

**Comment by brianPlummer** [comment]
@funyoung thanks for catching this! i have just fixed and pushed 0.0.9 up to maven.  i will update the readme once it becomes available on maven central.  thanks again!!

https://github.com/brianPlummer/TinyDancer/commit/30a34e60850d5fb6832bd7ae1c9defd4075a7907
